[package]
name = "falling_sand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.2"
bevy = "0.14.2"
iyes_perf_ui = "0.3.0"
